### PR TITLE
Quicksort. cpp

### PR DESCRIPTION
**Pull request by Priyanshu729**

### CODE REVIEW

**Comment by Priyanshu729** [comment]
Pls accept my pull request.And add hacktoberfest badge

**Comment by ANKIT9761** [comment]
Plz upload your code in proper structured format .
The format is -
Languagename/personname/codefile

**Comment by Priyanshu729** [comment]
Sir please add hacktoberfest badge🥺🥺

**Comment by Priyanshu729** [comment]
@ANKIT9761 can u please merge and add hacktoberfest badge??

**Pull request closed without merging**
